ais_serial_node:
  ros__parameters:
    ais_serial_port_name: "/dev/ttyUSB0"
    ais_baud_rate: 38400
    ais_topic_name: "/edge_server/external/ais/ship"
    ais_frame_id: "ais"
    ais_verbose: false
    ais_checksum_required: true
    ais_poll_period_sec: 0.005
    ais_read_size: 8192
    ais_reconnect_sec: 2.0
    ais_stale_static_info_sec: 600.0
